//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlDatabase.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlDatabase.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在针对对象({0})进行如下操作{1}时发生了异常:{2}.
        /// </summary>
        internal static string ChangeActionError {
            get {
                return ResourceManager.GetString("ChangeActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库关闭.
        /// </summary>
        internal static string DatabaseClosed {
            get {
                return ResourceManager.GetString("DatabaseClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库启动.
        /// </summary>
        internal static string DatabaseOpened {
            get {
                return ResourceManager.GetString("DatabaseOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除了一个对象，编号为{0}, 对象为{1}.
        /// </summary>
        internal static string DeleteObject {
            get {
                return ResourceManager.GetString("DeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除对象{0}时遇到异常: 该对象不存在或者文件不存在.
        /// </summary>
        internal static string DeleteObjectError {
            get {
                return ResourceManager.GetString("DeleteObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库运行期间发生了一般性异常，消息为:{0}.
        /// </summary>
        internal static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增了一个对象,编号为:{0},对象为:{1}.
        /// </summary>
        internal static string InsertObject {
            get {
                return ResourceManager.GetString("InsertObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进行了对象查询，取得的对象数量是:{0}.
        /// </summary>
        internal static string QueryObject {
            get {
                return ResourceManager.GetString("QueryObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成对类型{0}的配置.
        /// </summary>
        internal static string TypeConfiguration {
            get {
                return ResourceManager.GetString("TypeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新了一个对象,编号为:{0},对象为:{1}.
        /// </summary>
        internal static string UpdateObject {
            get {
                return ResourceManager.GetString("UpdateObject", resourceCulture);
            }
        }
    }
}
